### ISSUE TITLE
tangy-gui-uqdlogic16, cannot import name 'UQDLogic16' from 'tangy'

### ISSUE THREAD

**Issue by FarisRedza** [Peter-Barrow/tangy#1]
**Describe the bug**
ImportError from running `tangy-gui-uqdlogic16`

**To Reproduce**
Running `tangy-gui-uqdlogic16` results in
```
Traceback (most recent call last):
  File "/home/faris/Projects/tangy-test/.venv/bin/tangy-gui-uqdlogic16", line 5, in <module>
    from tangy.apps.gui_uqd import run
  File "/home/faris/Projects/tangy-test/.venv/lib/python3.10/site-packages/tangy/apps/gui_uqd.py", line 10, in <module>
    from tangy import tangy_config_location, UQDLogic16
ImportError: cannot import name 'UQDLogic16' from 'tangy' (/home/faris/Projects/tangy-test/.venv/lib/python3.10/site-packages/tangy/__init__.py)
```

**System (please complete the following information):**
 - Ubuntu
 - 22.04

**Additional context**
The `__init__.py` file shown in the error has the lines
```
# uqd_lib = None
# 
# if platform.startswith("linux"):
#     uqd_lib = find_library("timetag64")
# 
# if platform.startswith("win32"):
#     uqd_lib = find_library("CTimeTagLib")
#     from ._uqd import UQDLogic16
# 
# if uqd_lib is not None:
#     from ._uqd import UQDLogic16
```
commented out, uncommenting these lines fixes the issue and `tangy-gui-uqdlogic16` seems to work normally

**Comment by Peter-Barrow** [comment]
Thanks, this should be resolved in fb6d54e. A new revision 0.5.2 has been pushed to PyPi
