### ISSUE TITLE
tangy-gui-uqdlogic16, 'tangy._tangy.TangyBuffer' object has no attribute 'clear'

### ISSUE THREAD

**Issue by FarisRedza** [Peter-Barrow/tangy#3]
**Describe the bug**
When pressing start on tangy-gui-uqdlogic16, an attribute error is thrown and it does not start counting

**To Reproduce**
Apply a config and press start results in
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/jh115/Projects/waveguide/.venv/lib/python3.10/site-packages/tangy/apps/gui_uqd.py", line 368, in sync
    self.device.start_timetags()
  File "tangy_src/_uqd.py", line 370, in tangy._uqd.UQDLogic16.start_timetags
AttributeError: 'tangy._tangy.TangyBuffer' object has no attribute 'clear'

```

**System (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Additional context**
The file `tangy_src/_uqd.py` had the lines
```
  def start_timetags(self):
      """
      Start transmitting timetags from the device to the host computer
      """

      if self._have_buffer is True:
          self._buffer.clear()
```
in v0.4.1, where `_buffer.clear()` appears to have since been deprecated

**Comment by Peter-Barrow** [comment]
Fixed in e8edd83, please update install 0.5.3 from pypi
